name: uav_processing311
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - affine
  - attrs
  - blinker
  - blosc
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cycler
  - dash-leaflet
  - fiona
  - folium
  - freetype
  - freexl
  - gdal
  - geobuf
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - giflib
  - h2
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - itsdangerous
  - jinja2
  - json-c
  - keyutils
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libarchive
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libcxxabi
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libfreetype
  - libfreetype6
  - libgcc
  - libgcc-ng
  - libgdal-core
  - libgfortran
  - libgfortran5
  - libgomp
  - libhwy
  - libiconv
  - libjpeg-turbo
  - libjxl
  - libkml
  - liblapack
  - liblzma
  - libnghttp2
  - libnsl
  - libopenblas
  - libpng
  - librttopo
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - matplotlib-base
  - minizip
  - munkres
  - muparser
  - ncurses
  - nest-asyncio
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pip
  - proj
  - pthread-stubs
  - pycparser
  - pyogrio
  - pyparsing
  - pyproj
  - pysocks
  - python=3.11.13
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - qhull
  - rasterio
  - readline
  - requests
  - rtree
  - setuptools
  - shapely
  - six
  - snappy
  - snuggs
  - sqlite
  - threadpoolctl
  - tk
  - tzdata
  - unicodedata2
  - uriparser
  - wheel
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - altair
      - antspyx
      - anyio
      - anywidget
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asttokens
      - async-lru
      - babel
      - beautifulsoup4
      - bleach
      - cachetools
      - cmocean
      - comm
      - contourpy
      - dash
      - dash-bootstrap-components
      - dash-mantine-components
      - dataclasses-json
      - debugpy
      - decorator
      - deepdiff
      - defusedxml
      - deprecated
      - dipy
      - executing
      - fastjsonschema
      - filelock
      - flask
      - fonttools
      - fqdn
      - frozenlist
      - fsspec
      - fury
      - gitdb
      - gitpython
      - h11
      - h5py
      - httpcore
      - httpx
      - imageio
      - importlib-resources
      - ipykernel
      - ipython
      - ipython-pygments-lexers
      - ipywidgets
      - isoduration
      - itk
      - itk-core
      - itk-elastix
      - itk-filtering
      - itk-io
      - itk-numerics
      - itk-registration
      - itk-segmentation
      - jedi
      - joblib
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyter-client
      - jupyter-core
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - jupyterlab-widgets
      - kiwisolver
      - lazy-loader
      - marshmallow
      - matplotlib
      - matplotlib-inline
      - mistune
      - mpmath
      - multidict
      - mypy-extensions
      - narwhals
      - nbclient
      - nbconvert
      - nbformat
      - networkx
      - nibabel
      - notebook
      - notebook-shim
      - numpy
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - opencv-python
      - orderly-set
      - overrides
      - pandocfilters
      - parso
      - patsy
      - pexpect
      - pillow
      - platformdirs
      - plotly
      - prometheus-client
      - prompt-toolkit
      - propcache
      - protobuf
      - psutil
      - psygnal
      - ptyprocess
      - pure-eval
      - pyarrow
      - pydeck
      - pygltflib
      - pygments
      - python-json-logger
      - pyyaml
      - pyzmq
      - referencing
      - retrying
      - rfc3339-validator
      - rfc3986-validator
      - rpds-py
      - scikit-image
      - scikit-learn
      - scipy
      - send2trash
      - setuptools-scm
      - smmap
      - soupsieve
      - spectral
      - stack-data
      - statsmodels
      - streamlit
      - sympy
      - tenacity
      - terminado
      - tifffile
      - tinycss2
      - toml
      - torch
      - tornado
      - tqdm
      - traitlets
      - triton
      - trx-python
      - typing-extensions
      - typing-inspect
      - uri-template
      - urllib3
      - vtk
      - watchdog
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - werkzeug
      - widgetsnbextension
      - wrapt
      - yarl
